FROM centos/python-27-centos7
MAINTAINER Juan Diego Godoy Robles
USER root

RUN yum install dnf --assumeyes
RUN yum install python-devel python-distribute python-pip  --assumeyes

RUN pip install fabric
